### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by ravigoudar** [jelathro/C#4]
Develop a discussion forum for VTU students. 

It should have functionalitiess such as, 
Login from Stackoverflow or Quora 
support for profile pictures.
 An user can start a discussion, comment on others discussion,
User submitted question can be shared on quora and other popular platforms.

**Comment by kioscar** [comment]
Excuse me, i need help with a program
i have to do a program to calculate the factorial of a number but using process, the program ask the number and how many process will do.

**Comment by himanshujhamb222** [comment]
I can help you kioscar with the factorials program.

**Comment by himanshujhamb222** [comment]
#include<stdio.h>
int sigma(int m);
int main (void)

 {
     int n;
      do
      {
        printf("Give me a positive integer:");
        n=GetInt();
      }
    while(n<1);
    
    int answer=sigma(n);
    printf("sum of first %i natural no is %i\n",n,answer);
 }
 
    int sigma(int m)
   { 
       if(m<=0)
        {
           return 0;
        }
    
      else
        {
          return m+sigma(m-1);
        }
  }

**Comment by kioscar** [comment]
himanshujhamb222 Thanks :+1:
