### ISSUE TITLE
Memory allocation

### ISSUE THREAD

**Issue by ivenpoker** [jelathro/C#9]
- In the Hashtable module, most memory allocation doesn't check if the allocation was successful. 
  it rather assumes a success, as such can lead to runtime errors, where a pointer to a structure will 
  try to reference a structure member which doesn't exists. (this is same for all calls to 'malloc' and 
  'calloc' in the the other modules like those of Queues...)

**Comment by ivenpoker** [comment]
I fixed the issues listed above, but couldn't do a push after cloning and committing. Please could someone help!

**Comment by jelathro** [comment]
@ivenpoker you can create a pull request with your edits then I can merge them in from there.  I think you need to fork the repository first though.  This link might help https://help.github.com/articles/working-with-forks/
